[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "exact-ai"                  # Your package name on PyPI
version = "0.1.0"                  # Semantic version
description = "Comprehensive Library for explainable AI (XAI) methods."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Glenn Mathews", email = "glennmathews18@gmail.com" },
  { name = "Harishankar S M, email = "harishankarsm2004@gmail.com" },
  { name = "Afzina Sadiq, email = "afzinasadiq180@gmail.com" },
  { name = "Nandana Murali, email = "nandanalmurali2003@gmail.com" }
]
keywords = ["xai", "explainability", "gradcam", "lime", "shap", "ml", "ai"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
requires-python = ">=3.8"

# Runtime dependencies (all required)
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "matplotlib",
    "pillow",
    "grad-cam",
    "lime",
    "shap"
]  

[project.urls]
Homepage = "https://github.com/GurenMashu/E.X.A.C.T-by-GHAN"
#Documentation = "https://github.com/yourusername/mlmodels/wiki"
Source = "https://github.com/GurenMashu/E.X.A.C.T-by-GHAN"
#Tracker = "https://github.com/yourusername/mlmodels/issues"

[tool.setuptools]
package-dir = {"" = "src"}   # tells setuptools where your code lives

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]         # don’t ship tests to PyPI